stages:
  text_preprocessing:
    cmd: python main.py --stage text_preprocessing
    deps:
      - main.py
      - src/utils/data_loader.py
      - src/utils/logging_setup.py
      - src/data/text_preprocessing.py
      - configs/config.yaml
      - data/raw/IMDB Dataset.csv
    params:
      - params.yaml:
          - experiment.name
          - data.text_column
    outs:
      - data/processed/cleaned_data.csv

  train_val_test_split:
    cmd: python main.py --stage train_val_test_split
    deps:
      - main.py
      - src/utils/data_loader.py
      - src/utils/logging_setup.py
      - src/data/train_val_test_split.py
      - configs/config.yaml
      - data/processed/cleaned_data.csv
    params:
      - params.yaml:
          - data.text_column
          - data.target_column
          - split.test_size
          - split.val_size
          - split.random_state
          - split.stratify
    outs:
      - data/split/train.csv
      - data/split/valid.csv
      - data/split/test.csv