stages:
  data_loader:
    cmd: python main.py
    deps:
      - main.py
      - src/data/data_loader.py
      - data/raw/IMDB Dataset.csv
      - params.yaml
    params:
      - data.raw.raw_path
      - data.save_data.dest_path
    

