stages:
  text_preprocessing:
    cmd: python main.py
    deps:
      - main.py
      - src/utils/data_loader.py
      - src/utils/logging_setup.py
      - src/data/text_preprocessing.py
      - configs/config.yaml
      - data/raw/IMDB Dataset.csv
    params:
      - experiment.name
      - data.text_column
    outs:
      - data/processed/cleaned_data.csv
  
  # # Stage 2: Text cleaning
  # text_cleaning:
  #   cmd: python main.py +stage=text_cleaning
  #   deps:
  #     - main.py
  #     - src/data/text_cleaning.py
  #     - data/processed/cleaned_data.csv
  #     - params.yaml
  #   params:
  #     - params.yaml:
  #         - data.save_data.dest_path
  #         - data.cleaned.cleaned_path
  #   outs:
  #     - data/cleaned/text_cleaned.csv

  # preprocess:
  #   cmd: python main.py
    
  #   deps:
  #     - main.py
  #     - params.yaml
  #     - configs/logging.yaml
  #     - configs/config.yaml
  #     - src/data/data_loader.py
  #     - data/raw/IMDB Dataset.csv
  #     - src/data/logging_setup.py
  #     - src/data/text_preprocessing.py
    
  #   params:
  #     - data.text_column
  #     - data.target_column
    
  #   outs:
  #     - data/processed/cleaned_data.csv

