stages:
  preprocess:
    cmd: python main.py text_preprocesing
    
    deps:
      - main.py
      - params.yaml
      - configs/config.yaml
      - src/data/data_loader.py
      - data/raw/IMDB Dataset.csv
      - src/data/logging_setup.py
      - src/data/text_preprocessing.py
    
    params:
      - data.text_column
      - data.target_column

    outs:
      - data/processed/cleaned_data.csv

 