data:
<<<<<<< HEAD
  raw:
    raw_path: data/raw/IMDB Dataset.csv

  save_data:
    dest_path: data/processed/cleaned_data.csv

  cleaned:
    cleaned_path: data/cleaned/text_cleaned.csv

  text_data:
    text_path: data/cleaned/text_cleaned.csv
  
=======
  text_column: review
  target_column: sentiment
  

experiment:
  name: exp_1
>>>>>>> master
