data:
  raw:
    raw_path: data/raw/IMDB Dataset.csv

  save_data:
    dest_path: data/processed/cleaned_data.csv

  cleaned:
    cleaned_path: data/cleaned/text_cleaned.csv

  split:
    train_path: data/Split/train.csv
    val_path: data/Split/val.csv
    test_path: data/Split/test.csv
    test_size: 0.2
    val_size: 0.25
    random_state: 42
    feature_column: 'review'
    target_column: 'sentiment'
    stratify: true

  vectorization:
    path: data/vectorize
    model_name: distilbert-base-uncased

model:
  model_name: "distilbert-base-uncased"
  num_labels: 2
  freeze_base: true
  cache_dir: null

path:
  output_dir: "outputs/"

train:
  epochs: 1
  batch_size: 32
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 50
  eval_steps: 100
  save_steps: 500
  early_stopping_patience: 3
  experiment_name: "my_experiment"
  run_name: null